# -*- coding: utf-8 -*-
"""New Resnet.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wwMi9WV6fdqUmWbziE9cCX8RmHlgTunn
"""



import tensorflow as tf
from tensorflow.keras.preprocessing.image import ImageDataGenerator
from tensorflow.keras.applications import ResNet50
from tensorflow.keras.layers import Dense, GlobalAveragePooling2D, Dropout
from tensorflow.keras.models import Model
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.callbacks import EarlyStopping, ModelCheckpoint
from sklearn.utils import class_weight
import numpy as np
import os
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.metrics import confusion_matrix, classification_report, roc_curve, auc

# --- 1. Configuration and Paths ---
IMAGE_SIZE = (224, 224) # Standard input size for ResNet50
BATCH_SIZE = 32
NUM_CLASSES = 2 # Defect, Non Defect (or vice versa based on your labeling)
EPOCHS = 20 # Start with a reasonable number, early stopping will prevent overfitting
LEARNING_RATE = 0.0001 # Start with a small learning rate for transfer learning

# Define your dataset paths
# Ensure these paths correctly point to your 'train' and 'test' folders
# and that 'train' and 'test' each contain 'Defect' and 'Non Defect' subfolders.
TRAIN_DIR = "/content/drive/MyDrive/Railway_Fault_Dataset" # e.g., 'C:/Users/YourUser/Desktop/Railway_Fault_Dataset/train'
TEST_DIR = "/content/drive/MyDrive/Railway_Fault_Dataset_Test" # e.g., 'C:/Users/YourUser/Desktop/Railway_Fault_Dataset_Test/test'


# --- 2. Data Loading and Augmentation ---

# Data Augmentation for Training
# Apply various transformations to make the model robust
train_datagen = ImageDataGenerator(
    rotation_range=20,        # Rotate images by 20 degrees
    width_shift_range=0.1,    # Shift images horizontally by 10%
    height_shift_range=0.1,   # Shift images vertically by 10%
    shear_range=0.1,          # Shear intensity
    zoom_range=0.1,           # Random zoom
    horizontal_flip=True,     # Randomly flip images horizontally
    fill_mode='nearest',      # Fill pixels that appear after transformations
    preprocessing_function=tf.keras.applications.resnet50.preprocess_input # ResNet specific preprocessing
)

# No augmentation for validation/test data, only resizing and preprocessing
test_datagen = ImageDataGenerator(
    preprocessing_function=tf.keras.applications.resnet50.preprocess_input
)

# Load data from directories
# class_mode='binary' for two classes (0 or 1)
train_generator = train_datagen.flow_from_directory(
    TRAIN_DIR,
    target_size=IMAGE_SIZE,
    batch_size=BATCH_SIZE,
    class_mode='binary', # Assumes 'Defect' and 'Non Defect' are your folder names
    shuffle=True
)

test_generator = test_datagen.flow_from_directory(
    TEST_DIR,
    target_size=IMAGE_SIZE,
    batch_size=BATCH_SIZE,
    class_mode='binary',
    shuffle=False # Do not shuffle test data to maintain order for evaluation
)

# Get class indices from the generator to calculate class weights
# This assumes 'Defect' maps to 0 and 'Non Defect' maps to 1 based on alphanumeric order of folder names.
# Verify this by printing train_generator.class_indices if needed.
class_indices = train_generator.class_indices
# e.g., {'Defect': 0, 'Non Defect': 1} or {'Non Defect': 0, 'Defect': 1}
print("Class Indices:", class_indices)

# --- 3. Handle Class Imbalance ---
# Calculate class weights to give more importance to the minority class (Non Defect based on your numbers)
# This helps the model pay more attention to the under-represented class.

# In your case, 'Defect' is 1067 and 'Non Defect' is 441 in training.
# So, 'Non Defect' is the minority class.
# The calculation for class_weights typically assigns a higher weight to the minority class.
# Ensure the labels '0' and '1' correspond to 'Defect' and 'Non Defect' as per flow_from_directory.
# flow_from_directory assigns labels alphabetically by folder name.
# If your folders are 'Defect' and 'Non Defect':
#   'Defect' will be class 0, 'Non Defect' will be class 1.
#   So, you'd want to weigh class 1 higher.

class_weights = class_weight.compute_class_weight(
    class_weight='balanced',
    classes=np.unique(train_generator.classes),
    y=train_generator.classes
)
class_weights = dict(enumerate(class_weights))
print("Calculated Class Weights:", class_weights)

# --- 4. Build the Model (Transfer Learning with ResNet50) ---

# Load the ResNet50 model pre-trained on ImageNet data
# include_top=False means we don't include the original classification head
base_model = ResNet50(weights='imagenet', include_top=False, input_shape=(IMAGE_SIZE[0], IMAGE_SIZE[1], 3))

# Freeze the convolutional base layers so they are not trained
# This uses the pre-learned features as is.
for layer in base_model.layers:
    layer.trainable = False

# Add your custom classification head
x = base_model.output
x = GlobalAveragePooling2D()(x) # Reduces spatial dimensions, keeping global features
x = Dense(256, activation='relu')(x) # A dense layer
x = Dropout(0.5)(x) # Dropout for regularization to prevent overfitting
predictions = Dense(NUM_CLASSES - 1 if NUM_CLASSES == 2 else NUM_CLASSES, activation='sigmoid' if NUM_CLASSES == 2 else 'softmax')(x) # Output layer

# If binary classification (2 classes), use sigmoid and 1 neuron.
# If multi-class (>2 classes), use softmax and NUM_CLASSES neurons.
# For anomaly detection (binary), sigmoid is appropriate for a single output neuron
# that gives the probability of being the positive class (e.g., "Non Defect").
# If you configure class_mode='categorical' for 2 classes, then use softmax and 2 neurons.
# Here, assuming `class_mode='binary'` for 2 classes, so `sigmoid` and 1 neuron for `predictions`.
# Let's adjust for binary case with 1 output neuron:
if NUM_CLASSES == 2:
    predictions = Dense(1, activation='sigmoid')(x) # Single neuron for binary classification
else:
    predictions = Dense(NUM_CLASSES, activation='softmax')(x)


model = Model(inputs=base_model.input, outputs=predictions)

# --- 5. Compile the Model ---
model.compile(optimizer=Adam(learning_rate=LEARNING_RATE),
              loss='binary_crossentropy' if NUM_CLASSES == 2 else 'categorical_crossentropy',
              metrics=['accuracy',
                        tf.keras.metrics.Precision(name='precision'),
                        tf.keras.metrics.Recall(name='recall'),
                        tf.keras.metrics.AUC(name='auc')])

model.summary()

# --- 6. Train the Model ---

# Callbacks for better training control
early_stopping = EarlyStopping(monitor='val_loss', patience=10, restore_best_weights=True)
model_checkpoint = ModelCheckpoint('best_model.h5', monitor='val_loss', save_best_only=True)

history = model.fit(
    train_generator,
    epochs=EPOCHS,
    validation_data=test_generator, # Using test_generator as validation here, consider a separate validation set if possible
    class_weight=class_weights, # Apply calculated class weights
    callbacks=[early_stopping, model_checkpoint]
)

# --- 7. Evaluate the Model ---

print("\n--- Evaluating on Test Data ---")
loss, accuracy, precision, recall, auc_score = model.evaluate(test_generator)

print(f"Test Loss: {loss:.4f}")
print(f"Test Accuracy: {accuracy:.4f}")
print(f"Test Precision: {precision:.4f}")
print(f"Test Recall: {recall:.4f}")
print(f"Test AUC: {auc_score:.4f}")

# Generate predictions for confusion matrix and classification report
print("\n--- Generating Classification Report ---")
# Get true labels and predicted probabilities
test_labels = test_generator.classes
test_filenames = test_generator.filenames
# Predict probabilities for the positive class (e.g., 'Non Defect' if it's class 1)
y_pred_probs = model.predict(test_generator)

# Convert probabilities to binary predictions (0 or 1)
# Default threshold is 0.5. You might want to tune this for anomaly detection.
y_pred_binary = (y_pred_probs > 0.5).astype(int).flatten()

# Get the mapping from class index to class name
labels_map = {v: k for k, v in class_indices.items()}
target_names = [labels_map[i] for i in sorted(labels_map.keys())]

# Confusion Matrix
cm = confusion_matrix(test_labels, y_pred_binary)
plt.figure(figsize=(8, 6))
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues',
            xticklabels=target_names,
            yticklabels=target_names)
plt.xlabel('Predicted Label')
plt.ylabel('True Label')
plt.title('Confusion Matrix')
plt.show()

# Classification Report
print(classification_report(test_labels, y_pred_binary, target_names=target_names))

# ROC Curve
fpr, tpr, thresholds = roc_curve(test_labels, y_pred_probs)
roc_auc = auc(fpr, tpr)

plt.figure()
plt.plot(fpr, tpr, color='darkorange', lw=2, label=f'ROC curve (area = {roc_auc:.2f})')
plt.plot([0, 1], [0, 1], color='navy', lw=2, linestyle='--')
plt.xlim([0.0, 1.0])
plt.ylim([0.0, 1.05])
plt.xlabel('False Positive Rate')
plt.ylabel('True Positive Rate')
plt.title('Receiver Operating Characteristic (ROC) Curve')
plt.legend(loc="lower right")
plt.show()

# --- 8. Plotting Training History ---
plt.figure(figsize=(12, 5))

# Plot training & validation accuracy values
plt.subplot(1, 2, 1)
plt.plot(history.history['accuracy'])
plt.plot(history.history['val_accuracy'])
plt.title('Model Accuracy')
plt.ylabel('Accuracy')
plt.xlabel('Epoch')
plt.legend(['Train', 'Validation'], loc='upper left')

# Plot training & validation loss values
plt.subplot(1, 2, 2)
plt.plot(history.history['loss'])
plt.plot(history.history['val_loss'])
plt.title('Model Loss')
plt.ylabel('Loss')
plt.xlabel('Epoch')
plt.legend(['Train', 'Validation'], loc='upper left')
plt.show()

from google.colab import drive
drive.mount('/content/drive')

# Save the entire model to Google Drive
model_path = '/content/drive/MyDrive/railway_defect_detector.h5'  # Path in Google Drive
model.save(model_path)  # Save the model

print(f"Model saved at {model_path}")

from tensorflow.keras.models import load_model

# Mount Google Drive (required every new Colab session)
from google.colab import drive
drive.mount('/content/drive')

# Load the saved model from Google Drive
model_path = '/content/drive/MyDrive/railway_defect_detector.h5'
loaded_model = load_model(model_path)

# Verify the model is loaded properly
loaded_model.summary()

# Now you can proceed with Grad-CAM or any other operations

import tensorflow as tf
import numpy as np
import matplotlib.pyplot as plt
import cv2 # OpenCV for image processing (resizing, colormaps)
from tensorflow.keras.preprocessing import image
from tensorflow.keras.applications.resnet50 import preprocess_input # For ResNet-specific preprocessing
import os

# --- Configuration ---
IMAGE_SIZE = (224, 224) # Standard input size for ResNet50

# --- 1. Grad-CAM Function Definition ---
# (Your make_gradcam_heatmap and save_and_display_gradcam functions go here, unchanged from what you provided)
def make_gradcam_heatmap(img_array, model, last_conv_layer_name, pred_index=None):
    """
    Generates a Grad-CAM heatmap for a given image and model.
    """
    # Create a model that maps the input image to the activations of the last conv layer
    # as well as the output predictions.
    grad_model = tf.keras.models.Model(
        [model.inputs], [model.get_layer(last_conv_layer_name).output, model.output]
    )

    # Compute the gradient of the top predicted class for our input image
    # with respect to the activations of the last conv layer.
    with tf.GradientTape() as tape:
        last_conv_layer_output, preds = grad_model(img_array)
        if pred_index is None:
            if preds.shape[-1] == 1:
                pred_index = (tf.cast(preds[0] > 0.5, tf.int32)).numpy()[0]
            else: # For softmax multi-class
                pred_index = tf.argmax(preds[0]).numpy()

        if model.output.shape[-1] == 1: # Binary classification with sigmoid
            if pred_index == 1: # Explaining the positive class (e.g., 'Non Defect')
                class_output_score = preds[0, 0]
            else: # Explaining the negative class (e.g., 'Defect')
                class_output_score = 1 - preds[0, 0]
        else: # Multi-class with softmax
            class_output_score = preds[:, pred_index]

    grads = tape.gradient(class_output_score, last_conv_layer_output)
    pooled_grads = tf.reduce_mean(grads, axis=(0, 1, 2))
    last_conv_layer_output = last_conv_layer_output[0]
    heatmap = last_conv_layer_output @ pooled_grads[..., tf.newaxis]
    heatmap = tf.squeeze(heatmap)
    heatmap = tf.maximum(heatmap, 0) / tf.math.reduce_max(heatmap)
    return heatmap.numpy()

def save_and_display_gradcam(img_path, heatmap, cam_path="cam.jpg", alpha=0.4):
    """
    Overlays the heatmap on the original image and saves/displays it.
    """
    img = image.load_img(img_path)
    img = image.img_to_array(img)
    heatmap = np.uint8(255 * heatmap)
    jet = plt.cm.jet
    jet_colors = jet(np.arange(256))[:, :3]
    jet_heatmap = jet_colors[heatmap]
    jet_heatmap = image.array_to_img(jet_heatmap)
    jet_heatmap = jet_heatmap.resize((img.shape[1], img.shape[0]))
    jet_heatmap = image.img_to_array(jet_heatmap)
    superimposed_img = jet_heatmap * alpha + img
    superimposed_img = tf.keras.utils.array_to_img(superimposed_img)
    superimposed_img.save(cam_path)
    plt.imshow(superimposed_img)
    plt.axis('off')
    plt.title(f"Grad-CAM for {os.path.basename(img_path)}")
    plt.show()

# --- 2. Load your trained model ---
# Define the path to your saved model file
# IMPORTANT: This path MUST match where you saved it in your training script.
# If you used ModelCheckpoint('best_model.h5') without a path, it's in the same directory.
# If you saved to Google Drive, use the full '/content/drive/My Drive/...' path.

# Choose one of these:
# Option A: If you saved as .h5 (from previous ModelCheckpoint)
model_load_path = 'best_model.h5'

# Option B: If you saved as .keras (recommended, if you updated your save code)
# model_load_path = 'my_railway_anomaly_detector_model.keras'

# Option C: If you saved to Google Drive (recommended for Colab/Jupyter persistence)
# from google.colab import drive
# drive.mount('/content/drive')
# model_load_path = '/content/drive/My Drive/Your_Research_Folder/Saved_Models/best_model.h5' # Adjust this!


try:
    model = tf.keras.models.load_model(model_load_path)
    print(f"Model loaded successfully from {model_load_path}.")
except Exception as e:
    print(f"Error loading model: {e}")
    print(f"Please ensure '{model_load_path}' is the correct path to your saved model.")
    exit()

# --- 3. Identify the Last Convolutional Layer ---
LAST_CONV_LAYER_NAME = 'conv5_block3_out' # Adjust this if your ResNet50 layer name is different

# Verify the layer exists:
if LAST_CONV_LAYER_NAME not in [layer.name for layer in model.layers]:
    print(f"Warning: Layer '{LAST_CONV_LAYER_NAME}' not found in the model. Please check `model.summary()` to find the correct last convolutional layer name of your ResNet50 base.")
    conv_layers = [layer.name for layer in model.layers if 'conv' in layer.name.lower()]
    if conv_layers:
        LAST_CONV_LAYER_NAME = conv_layers[-1]
        print(f"Using '{LAST_CONV_LAYER_NAME}' as the last convolutional layer.")
    else:
        print("No convolutional layers found. Cannot proceed with Grad-CAM.")
        exit()

# --- 4. Select an image for Grad-CAM visualization ---
# Define your test directory if it's needed for other parts or random selection
# Ensure TEST_DIR is defined if you are uncommenting the line below
# TEST_DIR = 'path/to/your/Railway_Fault_Dataset_Test/test'
sample_image_path = "/content/drive/MyDrive/Railway_Fault_Dataset_Test/Defect/1743443804025.jpg" # Your specific image path

# Verify the sample image path
if not os.path.exists(sample_image_path):
    print(f"Error: Sample image not found at {sample_image_path}. Please update 'sample_image_path' to a valid image from your test set.")
    exit()

# Load and preprocess the image for prediction
img = image.load_img(sample_image_path, target_size=IMAGE_SIZE)
img_array = image.img_to_array(img)
img_array = np.expand_dims(img_array, axis=0)
img_array = preprocess_input(img_array)

# --- 5. Generate and Display Grad-CAM Heatmap ---

# Get the model's prediction for the chosen image
predictions = model.predict(img_array)
predicted_class_prob = predictions[0][0]
predicted_class_label = (predicted_class_prob > 0.5).astype(int)

# --- Define NUM_CLASSES and Get class names for display ---
# You need to define NUM_CLASSES and the labels_map explicitly here,
# as `train_generator` is not available in this script.
# Assuming your 'Defect' is class 0 and 'Non Defect' is class 1 (alphabetical order by default)
NUM_CLASSES = 2
labels_map = {0: 'Defect', 1: 'Non Defect'} # Make sure this matches your actual labels and their mapping

predicted_class_name = labels_map[predicted_class_label]

print(f"Image: {os.path.basename(sample_image_path)}")
print(f"Predicted Probability of Non Defect: {predicted_class_prob:.4f}")
print(f"Predicted Class: {predicted_class_name}")

heatmap = make_gradcam_heatmap(img_array, model, LAST_CONV_LAYER_NAME, pred_index=predicted_class_label)

save_and_display_gradcam(sample_image_path, heatmap)

print("\nGrad-CAM heatmap generated. The bright areas indicate regions the model focused on for its prediction.")
print("If the prediction was 'Defect', these areas are what the model identified as defective.")
print("If the prediction was 'Non Defect', these areas are what the model considered normal or not indicative of a defect.")